// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace InitialPrefabs.Msdf
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "msdf_atlas";



        [DllImport(__DllName, EntryPoint = "get_glyph_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Data get_glyph_data(byte* font_path, byte* str, Args args);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Data
    {
        public uint units_per_em;
        public ByteBuffer* glyph_data;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Args
    {
        public float angle;
        public float uniform_scale;
        public uint padding;
        public uint max_atlas_width;
        public uint point_size;
        public UVSpace uv_space;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
        public int element_size;
    }


    internal enum UVSpace : uint
    {
        Default = 0,
        OneMinusU,
        OneMinusV,
    }


}
