[package]
name = "msdf-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msdf = { path = "../msdf-rs/msdf" } 
ttf-parser = "0.20.0"
mint = "0.5.9"
image = "0.25.1"
regex = "1.10.4"
